### ISSUE TITLE
运行直接报错

### ISSUE THREAD

**Issue by 940842546** [Mufanc/Genshin-SmartFishingRod#4]
源码运行还是exe运行都报错
Traceback (most recent call last):
  File "main.py", line 53, in <module>
  File "main.py", line 21, in __init__
AssertionError
[53132] Failed to execute script 'main' due to unhandled exception!
Exception ignored in: <function Window.__del__ at 0x0000014AF6ABAC10>
Traceback (most recent call last):
  File "main.py", line 48, in __del__
AttributeError: 'Window' object has no attribute 'hMemDc'

**Comment by Mufanc** [comment]
这个不是我的项目哦，请到[对应项目](https://github.com/hgjazhgj/GenshinAutoFish)下提交 Issue
